server:
  port: 10011
spring:
  application:
    name: leyou-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lyj8330328/leyou-config-dev.git
  rabbitmq:
    host: 47.104.175.20
    username: /leyou
    password: leyou
    virtual-host: /leyou


management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
